
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615
//----------------------------------------------------

package com.example.proyecto1_23.Parser;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int MULTIPLICACION = 15;
  public static final int PUNTO = 11;
  public static final int DECIMAL = 26;
  public static final int DIVISION = 16;
  public static final int LLAVESABIERTO = 7;
  public static final int SUMA = 13;
  public static final int UP = 18;
  public static final int ERROR = 17;
  public static final int CORCHETESCERRADO = 10;
  public static final int FLOOR = 23;
  public static final int CEIL = 22;
  public static final int CORCHETESABIERTO = 9;
  public static final int PARENTESISCERRADO = 6;
  public static final int RIGHT = 21;
  public static final int PARENTESISABIERTO = 5;
  public static final int COMA = 12;
  public static final int LEFT = 20;
  public static final int COMENTARIOS = 4;
  public static final int ENTEROS = 25;
  public static final int EOF = 0;
  public static final int LLAVESCERRADO = 8;
  public static final int PUSH = 24;
  public static final int CADENAS = 27;
  public static final int error = 1;
  public static final int DOWN = 19;
  public static final int PUNTOCOMA = 2;
  public static final int ESPACIOS = 3;
  public static final int RESTA = 14;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "PUNTOCOMA",
  "ESPACIOS",
  "COMENTARIOS",
  "PARENTESISABIERTO",
  "PARENTESISCERRADO",
  "LLAVESABIERTO",
  "LLAVESCERRADO",
  "CORCHETESABIERTO",
  "CORCHETESCERRADO",
  "PUNTO",
  "COMA",
  "SUMA",
  "RESTA",
  "MULTIPLICACION",
  "DIVISION",
  "ERROR",
  "UP",
  "DOWN",
  "LEFT",
  "RIGHT",
  "CEIL",
  "FLOOR",
  "PUSH",
  "ENTEROS",
  "DECIMAL",
  "CADENAS"
  };
}

